spring.application.name=order
server.port=8092

#Configuration
server.servlet.context-path=/order-api
spring.datasource.url=jdbc:mysql://localhost:3306/appleverse_order_db

spring.datasource.username=root
spring.datasource.password=24173