spring.application.name=cart
server.port=8089

#Configuration
server.servlet.context-path=/cart-api
spring.datasource.url=jdbc:mysql://localhost:3306/appleverse_cart

spring.datasource.username=root
spring.datasource.password=24173
